### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ghost** [edubart/ddosmon#3]
Hi, i'm not sure why i fail at building this program, please halp.

:~/ddosmon/build# make
[  7%] Building CXX object CMakeFiles/ddosmon.dir/src/configmanager.cpp.o
In file included from <command-line>:0:0:
/root/ddosmon/src/headers.h:67:30: fatal error: libxml/xmlmemory.h: No such file or directory
compilation terminated.
CMakeFiles/ddosmon.dir/build.make:62: recipe for target 'CMakeFiles/ddosmon.dir/src/configmanager.cpp.o' failed
make[2]: *** [CMakeFiles/ddosmon.dir/src/configmanager.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ddosmon.dir/all' failed
make[1]: *** [CMakeFiles/ddosmon.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GasGeverij** [comment]
Oh looks like it was a depency 
i installed that but now i get 

[  7%] Building CXX object CMakeFiles/ddosmon.dir/src/configmanager.cpp.o
In file included from <command-line>:0:0:
/root/ddosmon/src/headers.h:74:17: fatal error: lua.h: No such file or directory
compilation terminated.
CMakeFiles/ddosmon.dir/build.make:62: recipe for target 'CMakeFiles/ddosmon.dir/src/configmanager.cpp.o' failed
make[2]: *** [CMakeFiles/ddosmon.dir/src/configmanager.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ddosmon.dir/all' failed
make[1]: *** [CMakeFiles/ddosmon.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
